eureka:
  client:
    service-url:
      defaultZone: http://localhost:8801/eureka/
spring:
  rabbitmq:
    host: 192.168.183.131
    port: 5672
    username: guest
    password: guest

server:
  port: 8803