spring:
  application:
    name: auth-service
  profiles:
#    include: secret #删掉这行!
    active: ${SPRING_PROFILE_ACTIVE:dev}
  cloud:
    stream:
      bindings:
        register-output:
          destination: register
          content-type: application/json

#写入你的小程序信息
wx:
  miniapp:
    appid: wxaea476668375cd93
    secret: 4b770d7888cca984672899d182aee7e8
    msgDataFormat: JSON

jwt:
  pvt-key-file-name: RSA.key
  pub-key-file-name: RSA.pub
  duration: 1D  #JWT 1天过期


